app/package.json, app/shell-window/ui/navbar.js, app/stylesheets/shell-window/toolbar-actions.less, package.json
Integrated SAFE Authenticator plugin.
Updated with safe auth pop-up feature.
=> SAFE Authenticator plugin integration

README.md, app/package.json, package.json
build process updated for adding the beaker plugin
=> chore/build_fix: build process updated

.gitmodules, app/background-process.js, app/package.json, package.json, shell_scripts/pack_authenticator.ps1, shell_scripts/pack_authenticator.sh
Integrated SAFE Authenticator as git submodule and added build scripts for it.
=> MAID-1972 Package authenticator with SAFE Browser

app/background-process.js
Resolved windows open url issue
=> fix/win_open_url: resolve windows open url issue

.gitignore, README.md, package.json, shell_scripts/pack_authenticator.js, shell_scripts/pack_authenticator.ps1, shell_scripts/pack_authenticator.sh
Updated README.md for build process.
Removed safe-app install from post install script.
Updated build script
=> feat/readme.md: update readme.md for build process

app/shell-window/ui/navbar.js, shell_scripts/pack_authenticator.ps1, shell_scripts/pack_authenticator.sh
Updated IPC handling for web application
=> MAID-2006 feat/handle_web_app: update to handle web app

app/package.json, shell_scripts/pack_authenticator.js
Updated build script to handle errors and print log instantly.
=> Update build script

shell_scripts/pack_authenticator.js, shell_scripts/pack_authenticator.ps1, shell_scripts/pack_authenticator.sh
Resolved build script issue on windows platform and updated Authenticator submodule.
=> Resolved build script issue on windows

app/background-process/plugins.js
Restriction the API to expose within its scheme.
=> Expose APIs within it's scheme

app/package.json
Updated with basic meta data of browser
=> Update basic meta data

app/package.json, package.json
Updated DOM APIs
Fix for for each iteration
=> version update to 0.2.0

package.json, scripts/main.js, scripts/pack_authenticator.ps1, scripts/pack_authenticator.sh
Resolved running rebuild after pack-authenticator command on windows.
=> Rebuild after packaging authenticator fix

scripts/main.js, scripts/pack_authenticator.ps1, scripts/pack_authenticator.sh
Resolved authenticator pack build process
=> Resolve authenticator pack build process

app/package.json
DOM API updates
Authenticator fixes
=> version change to 0.2.1

app/background-process/ui/windows.js, app/builtin-pages/views/safe-status.js, app/stylesheets/builtin-pages.less
Updated with home page UI.
Updated Authenticator submodule to latest.
=> Home page UI updated

app/package.json, package.json
Updated authenticator submodule to latest
Updated beaker-plugins deps
=> Update authenticator submodule

app/background-process/ui/windows.js, app/builtin-pages/com/sidenav.js, app/img/authenticator-logo-dark.svg, app/img/authenticator-logo.svg, app/shell-window/ui/navbar.js, app/stylesheets/shell-window/toolbar-actions.less
Replace Navbar Authenticator logo.
Replace SAFE Status icon with home icon.
Stop safe_proxy.pac file get downloaded.
Authorise popup permissions prefixed with chevron icon
=> MAID-2094 - UI fixes

app/shell-window/ui/navbar.js, app/stylesheets/shell-window/toolbar-actions.less
Added application ID to authorise popup.
=> Authorise popup with app ID

app/shell-window/ui/navbar.js
=> fix/typo: resolve typo in container phrase

app/shell-window/ui/navbar.js, app/stylesheets/shell-window/toolbar-actions.less
Updated popup UI to bring option to fixed on scroll.
=> MAID-2105 Pin Allow and Deny Option to bottom

app/builtin-pages/views/safe-status.js, app/package.json, app/stylesheets/builtin-pages.less
Fix min width and height for the landing page (beaker:home)
Updated authenticator submodule
Updated patch version
=> Resolve UI issues

app/stylesheets/builtin-pages.less
=> fix/ui_styling: update landing page styling

app/background-process.js, app/background-process/safe-storage/settings.js, app/background-process/safe-storage/store.js, app/package.json
Commented the safe-js logic and removed the dependency from package.json
=> MAID-2115 remove safe-js dependency

app/package.json
Updated beaker_plugin_safe_app and beaker_plugin_safe_authenticator to version 0.1.0-dev.0
=> Update beaker plugins to version 0.1.0-dev.0

app/lib/error-page.js, app/shell-window/pages.js
fix #74 - Resolve error 404 typo
=> Resolve error 404 typo

package.json, tasks/build/build.js
Create locales folder on build for Mac OS platform.
=> MAID-2108 Browser missing the locale folder on OSX

app/lib/error-page.js, app/shell-window/ui/navbar.js
fix #73 - resolve index.html not automatically read.
Error page text to support HTML entities.
This fix depended on safe_app_nodejs PR [101](https://github.com/maidsafe/safe_app_nodejs/pull/101)
=> fix/issue_#73: resolve issue #73

app/background-process/ui/window-menu.js, app/background-process/ui/windows.js, app/shell-window/command-handlers.js, app/shell-window/pages.js, appveyor.yml
Reenables the toggle safemode functionality in the browser for optionally accessing the clearnet.
=> Toggle safemode fix MAID-2122

app/background-process/ui/window-menu.js, app/shell-window/ui/navbar.js, app/stylesheets/shell-window/toolbar-actions.less
Updated following UI issues
On the main menu make toggle-safe-browsing as checkbox type
In Clearnet mode make HTTP as default protocol on autocomplete
Flip browser refresh icon horizontally
=> MAID-2181 UI update

app/background-process/plugins.js
Tweaks to plugin imports and schema assignment to enable `localhost` development with the DOM APIs.
Requires: https://github.com/maidsafe/beaker-plugin-safe-app/pull/48
=> Feat/plugins: Enabled multiple plugin/schemes to import the same apis

package.json, yarn.lock
and avoid errors for prod setup when devving.
=> fix/node_env: Add 'dev' declaration to dev scripts [MAID-2178]

app/package.json, app/registerProtocolHandlers.js, app/yarn.lock, package.json, yarn.lock
when creating protocol handler files
=> fix/linux-file-creation: Adds fs-extra to ensure write paths exist [MAID-2195]

app/lib/fg/import-web-apis.js
feat/enable_log: pass flag for enabling logs
Pass flag to enable logs on demand
Depends on [beaker-plugin-safe-app #55](https://github.com/maidsafe/beaker-plugin-safe-app/pull/55)
=> MAID-2107 - pass flag to enable rust logs

app/shell-window/ui/navbar.js, app/stylesheets/shell-window/toolbar-actions.less
Update to show Auth popup with own_container and no container
Capitalise Container permission for MD request.
Set title for container names.
=> Minor UI changes

app/background-process/ui/windows.js
Prevents webview crash on receipt of localhost://p:<port> responses.
To test:
- Clone a react boilerplate (https://github.com/alicoding/react-webpack-babel) 
- `yarn` and `yarn dev`
- visit `localhost://p:8888` in the browser.
Everything should be 'okay'.
-----
This might be an electron bug. I wasn't able to see any reason _why_ this was happening. Just managed to pinpoint the apparent source...
I'll post an issue in electron and see if I can't setup a repo for testing, as this feels a bit _hacky_
=> fix/localhost: Delete origin header from outbound localhost requests. [MAID-2264]

app/shell-window/ui/navbar.js
Resolved parsing objects instead of array of permission set.
=> Parse permission set

app/package.json, app/yarn.lock
to provide proper message string when auth login fails
=> fix/loginErrs: Updates RPC [MAID-2272]

app/background-process/protocols/beaker.js, app/builtin-pages.js, app/builtin-pages/com/sidenav.js, app/builtin-pages/views/favourites.js
Updated typo - favorites to favourites.
=> MAID-2293 Resolve favourites typo

app/shell-window/ui/navbar.js
Added default case for permission list on auth popup UI
=> MAID-2289 Fix Permission list issue on Auth Popup

app/shell-window/ui/navbar.js
Show different UI for re-authorise popup
=> MAID-2301 Re-authorise UI popup

app/shell-window/ui/navbar.js
Handle Unregistered client on different channel.
=> MAID-2300 handle unregistered client

app/background-process/ui/windows.js
Disable to open devtool on dev environment.
=> Disable dev tool

app/background-process/ui/windows.js, app/shell-window/ui/navbar.js
Updated to handle standard request format.
=> Standard request format

app/background-process.js, app/background-process/open-url.js, app/background-process/ui/windows.js
Reverts maidsafe/safe_browser#153
=> Revert "MAID-2308 Prevent destroyed object warnings with openURL"

app/background-process/safe-storage/actions/initializer_actions.js, app/background-process/safe-storage/safenet_comm.js, app/background-process/safe-storage/store.js, app/background-process/ui/windows.js
to not need the IPC auth listening hack.
=> fix/auth: Fix browser auth promise MAID-2318

app/shell-window/pages.js
for triggering http requests in safeMode without adding a new tab
=> fix/newTab: create temporary webview MAID-2338

app/background-process/safe-storage/safenet_comm.js, app/package.json, app/yarn.lock
Use the npm package of `maidsafe/safe-node-app`
=> chore/safe-app: Depend on NPM package for browser MAID-2332

app/package.json, app/yarn.lock, package.json, yarn.lock
Reverts maidsafe/safe_browser#168
=> Revert "chore/Upgrade safe_app_plugin to v0.2.2 and update yarn.lock files"

CHANGELOG.md, app/package.json, app/yarn.lock
**Change log**
- UI improvements
- uses authenticator plugin v0.3.0
- uses safe-app plugin v0.3.0
=> version change to 0.6.0

app/yarn.lock
=> fix/packages: Update yarn.lock for new safe packages

app/shell-window/pages.js
Successful test with PR: https://github.com/maidsafe/safe_browser/pull/201
=> replaces new URL with url.parse

app/shell-window/pages.js, app/shell-window/ui/tabs.js, package.json, tasks/build/bundle.js, yarn.lock
automatically only for service/id changes.
=> feat/handles: MAID-2390 Free app handles 

app/lib/README.md, package.json, scripts/main.js, yarn.lock
Incorporate changes to build/package for naming convention and version file.
This puts @shankar2105 's changes from https://github.com/maidsafe/safe_browser/pull/84 onto master.
=> feat/package: MAID-2124  Update build script of safe browser

CHANGELOG.md, app/package.json, app/yarn.lock, yarn.lock
Reverts maidsafe/safe_browser#220
=> Revert " chore/Version change to v0.6.1"

app/package.json, package.json, scripts/main.js, yarn.lock
modclean removed from scripts/main.js.
The sourcemap files were deleted in the modclean step before packaging, which was resulting in the file not found issue on authenticator when the dev console was opened.
=> fix/package: resolve authenticator file not found

CHANGELOG.md, app/package.json
Updated beaker plugins to 0.4.1
=> Update beaker plugins version

app/yarn.lock
Updated yarn.lock for beaker-plugins deps update
=> Updated yarn.lock

CHANGELOG.md, app/package.json, app/yarn.lock
Updated beaker plugin safe app to 0.4.2
=> Update beaker plugin safe app

app/shell-window/ui/navbar.js
=> Resolve path issue

app/shell-window/ui/navbar.js
Resolved address bar issue on clicking enter
=> Resolved address bar issue

CHANGELOG.md, app/background-process/plugins.js, app/lib/fg/import-web-apis.js, app/package.json, app/yarn.lock
This also includes the upgrade of safe-authenticator plugin to v0.4.3
=> MAID-2487 feat/plugin: Support for exposing objects declared in plugins as constants in the DOM API

CHANGELOG.md, README.md, app/background-process/safe-storage/safenet_comm.js, app/package.json, app/shell-window/pages.js, app/shell-window/ui/tabs.js, package.json, yarn.lock
This PR also includes a commit to fix issue MAID-2602 related to safeApp handles not being freed in a specific circumstance.
=> chore/dependencies: Version change to 0.10.2 upgrading electron to v1.8.4

CHANGELOG.md, __tests__/components/Notifier.spec.js, app/components/Notifier/Notifier.jsx, app/extensions/safe/components/authRequest.js, app/extensions/safe/ffi/authenticator.js, app/extensions/safe/ffi/ipc.js, app/extensions/safe/manageAuthNotifications.js, app/locales/en.json
I think the scope of the task was covered.
I didn't get too far into polishing notification UI because I need input on basic design and layout.
Discovered that am unable to authorise `shareMDataReqUri`, see note at `TODO/BOOKMARK`.
=> MAID-2687 chore/auth: pass auth info object notification

app/extensions/safe/actions/authenticator_actions.js, app/extensions/safe/auth-web-app/index.js, app/extensions/safe/auth-web-app/reducers/app.js, app/extensions/safe/ffi/authenticator.js, app/extensions/safe/ffi/ipc.js, app/extensions/safe/ffi/refs/parsers.js, app/extensions/safe/reducers/authenticator.js, app/extensions/safe/reducers/initialAppState.js, app/extensions/safe/webviewPreload.js
Why WIP?
See my comment on line 98.
=> MAID-2801 fix/auth: unlock icon prevents notification of previsouly authorised application

__e2e__/peruse.spec.js, app/components/AddressBar/ButtonsLHS/ButtonsLHS.jsx
e2e tests for backward/forward buttons
=> e2e tests for backward/forward

README.md
=> minor update in readme

app/components/Tab/Tab.jsx, webpack.config.renderer.dev.js
For #300.
Not sure if this can close that...
=> fix/devtools: Fix opening of devtools on webviews

LICENSE-BSD, LICENSE-MIT, README.md
updated readme license text and license files to updated license details
=> MAID-3125: docs/license: update LICENSE details

app/components/Tab/Tab.jsx, package.json, yarn.lock
Fixes #294 `does not have the selection to open a link in a new tab`
=> fix/newTabs: enable newTab context menu option for links.

app/extensions/safe/peruseSafeApp/index.js
Adds if/else for windows as it seems to be running both auth methods.
Fixes #332
=> Peruse app auth fix for windows

__tests__/utils/urlHelpers.spec.js, app/utils/urlHelpers.js
=> fix(Address bar url handling): No longer strip index/.html from urls

README.md
=> docs(Readme): Update readme to clarify normal and -dev versions

CHANGELOG.md, app/extensions/safe/auth-web-app/components/create_account.js
@joshuef @bochaco Note that this PR cannot be verified to resolve #281 until PR #315 is merged, after which the issue will exist as it currently only applies to SAFE Beaker Browser.
=> chore(auth): able to paste into input via context menu option and value be analyzed for password strength

app/openWindow.js
=> fix(browser-window): adds frame to browser window options (#362)

CHANGELOG.md, README.md, package.json, updateAppVersionWithChangelog.js, yarn.lock
Sorts #351 via addition of conventional-changelog.
=> Automate changelog creation and versioning

app/components/Tab/Tab.jsx, app/extensions/safe/webviewPreload.js
=> docs(Experiments): Warn when using experimental APIs in the DOM

app/extensions/safe/ffi/ipc.js
=> chore(auth): shifts enqueued request upon error

app/extensions/safe/auth-web-app/components/app_list.js
=> fix/typo: inverted apostrophe

app/components/Browser/Browser.jsx, app/components/Notifier/Notifier.jsx, app/extensions/safe/auth-web-app/components/app_list.js, app/extensions/safe/auth-web-app/components/login.js, app/extensions/safe/components/authRequest.js, app/extensions/safe/components/wrapBrowser.js
- fix router push PATH, and unique 'key' prop warnings
- fix window ID and webappkitregion warnings 
fixes #330
=> Fix devtools warnings

app/menu.js, app/openWindow.js, app/setupBackground.js
show the Browser app devtools in --debug mode after pack.
=> fix: show devtools in --debug mode after pack

package.json
=> fix(install): do a full build on 'yarn'

post-pack.js
=> fix(package): crust.config matches executable on Windows

__tests__/components/AddressBar.spec.js, __tests__/components/Browser.spec.js, __tests__/reducers/tabs.spec.js, app/components/AddressBar/AddressBar.jsx, app/components/AddressBar/ButtonsLHS/ButtonsLHS.jsx, app/extensions/safe/actions/authenticator_actions.js, app/reducers/tabs.js
resolves #418 
Also adds in disabled buttons when at the limit of history in either direction, and more tests!
=> Enhance back/forwards

app/package.json, app/yarn.lock
=> fix(webview): Update safe_app version to prevent webview crash.

app/extensions/safe/components/webIdDropdown/WebIdDropdown.js
=> chore(url): Update webIdMgr url

app/package.json, app/yarn.lock
=> chore(safe-node-app): Upgrade @maidsafe/safe-node-app dependency to v0.10.3

__e2e__/peruse.spec.js, app/components/AddressBar/AddressBar.jsx, app/components/CustomMenu/CustomMenu.jsx, app/constants.js, app/extensions/safe/components/wrapAddressBarButtonsRHS.js
=> test(settingsMenu): add e2e tests for settings menu

app/components/Tab/Tab.jsx
=> fix(webview): loads expected error after multiple subsequent invalid URI errors and localhost resource errors

__tests__/components/Error.spec.js, app/components/Browser/Browser.jsx, app/components/PerusePages/Error/Error.jsx, app/components/Tab/Tab.jsx, app/components/TabContents/TabContents.jsx
=> refactor(http-request): HTTP URL now shows notification and closes tab

__tests__/reducers/tabs.spec.js, app/reducers/tabs.js
=> fix(tabs): focuses reopened last tab

app/extensions/safe/index.js
=> fix(menu): Save/Read browser state menu options

app/extensions/safe/index.js
=> fix(electron-app): only calls setAsDefaultProtocolClient if non-packed && !win32

__e2e__/lib/browser-driver.js, app/extensions/safe/test/e2e/lib/authenticator-drivers.js
Resolves #565 (after other fixes) by reducing failed CI runs
=> fix(CI): Add missing WAIT for some auth CI drivers

app/containers/App.js, app/containers/Root.js, app/extensions/safe/auth-web-app/components/account_info.js, app/extensions/safe/auth-web-app/components/app.js, app/extensions/safe/auth-web-app/components/app_details.js, app/extensions/safe/auth-web-app/components/app_list.js, app/extensions/safe/auth-web-app/components/app_list_item.js, app/extensions/safe/auth-web-app/components/auth_loader.js, app/extensions/safe/auth-web-app/components/card_loader_full.js, app/extensions/safe/auth-web-app/components/create_account.js, app/extensions/safe/auth-web-app/components/login.js, app/extensions/safe/auth-web-app/components/network_status.js, app/extensions/safe/auth-web-app/components/popup.js, app/extensions/safe/components/webIdDropdown/WebIdDropdown.js, app/extensions/safe/components/wrapAddressBarButtonsLHS.js, app/extensions/safe/components/wrapAddressBarButtonsRHS.js, app/extensions/safe/components/wrapAddressBarInput.js, app/extensions/safe/components/wrapBrowser.js, app/extensions/safe/reducers/authenticator.js, app/menu.js, app/reducers/bookmarks.js, app/reducers/index.js, app/reducers/notifications.js, app/reducers/remoteCalls.js, app/reducers/tabs.js, app/reducers/ui.js, flow-typed/module_vx.x.x.js, internals/scripts/CheckNodeEnv.js, internals/scripts/CheckPortInUse.js
=> chore(Linting): Fix linting on some files

.travis.yml
For #565 
Moves prod pack to before deploy not on success to speed things up.
=> chore(CI): Move second package to before deploy, instead of on success

.travis.yml
for #565 
Updates naming of hash files for checksums
=> fix(CI): Travis release sha256 naming fixed

app/constants.js, app/logger.js, app/setupBackground.js
=> Fix mock packaging

__tests__/actions/ui.spec.js, app/actions/ui_actions.js, app/components/AddressBar/AddressBar.jsx, app/reducers/initialAppState.js, app/reducers/ui.js
=> fix(Menu):Remove local scoping

__tests__/actions/ui.spec.js, __tests__/components/Browser.spec.js, __tests__/reducers/ui.spec.js, app/actions/ui_actions.js, app/components/AddressBar/AddressBar.jsx, app/components/AddressBar/ButtonsRHS/ButtonsRHS.jsx, app/components/Browser/Browser.jsx, app/components/CustomMenu/CustomMenu.jsx, app/openWindow.js, app/reducers/initialAppState.js, app/reducers/ui.js
=> Fix(Menu): Scope open menu to Current Window only

CHANGELOG.md, package.json
=> chore(release): 0.11.2

README.md, docs/browser-development/Application-Design-Overview.md, docs/web-app-development/SAFE-Web-App-Overview.md
QA:
- Do links to web app doc work from `README.md`
- Do links to application design doc work from `README.md`
=> docs(App Structure): Simplify readme.md

.eslintrc.js, package.json, yarn.lock
QA: standard regression. This only affects lint rules.
=> chore(lint): Remove tslint as overkill

README.md, docs/browser-development/Application-Design-Overview.md, docs/web-app-development/SAFE-Web-App-Overview.md
QA: This is just touching documentation
=> docs(Readme): Enhance readme with table of contents.

app/extensions/safe/components/webIdDropdown/WebIdDropdown.tsx, app/extensions/safe/components/webIdDropdown/webIdButtons.css, app/extensions/safe/components/wrapAddressBarButtonsLHS.tsx
- Resolves error when clicking on `Authorise to display your WebIds`
Tracking #496
=> fix(ui): Adds antd spinner when waiting for webid's are fetching

app/extensions/safe/components/webIdDropdown/webIdButtons.css
Previously on master: 
https://www.dropbox.com/s/qw36g9a0q05kxva/Screenshot%202019-04-22%2012.04.01.jpg?dl=0
Now: sane positioning once more
https://www.dropbox.com/s/q68webx4syl1icw/Screenshot%202019-04-22%2012.07.55.jpg?dl=0
QA: WebId dropdown position should be as normal (previously was being pushed into the browser window)
=> fix(webId): Dropdown positioning fixed

__tests__/components/Tab.spec.tsx, app/components/Tab/Tab.tsx, app/extensions/safe/index.ts
=> fix(Links): Opening a link will only open in focussed browser window now

CHANGELOG.md, package.json
Please reference the issue(s) which this pull request addresses using [keywords](https://help.github.com/articles/closing-issues-using-keywords/) such as:
```
Resolves #452
Fixes #363
Closes #408
```
---
Provide QA team and reviewer steps to test the resolution.
For example:
```
QA:
Easiest way to test this PR would be to:
- Run API playground
- Initialise app
- Copy the value from [authReqWithoutMockBit](https://github.com/maidsafe/safe_browser/compare/master...hunterlester:454?expand=1#diff-a003f29f7e2f9aeecfe6e3fbb39e3d2eR30)
- Paste value into `authorise` operation and run
- Expect to see an error notification
- Same steps for [encodedNonExistentShareMDataReq](https://github.com/maidsafe/safe_browser/compare/master...hunterlester:454?expand=1#diff-a003f29f7e2f9aeecfe6e3fbb39e3d2eR28) …
```
=> chore(release): 0.13.0

app/openWindow.ts
=> fix(openWindow): use did-finish-load event for window open.

__tests__/components/AddressBarInput.spec.tsx, __tests__/components/Browser.spec.tsx, __tests__/reducers/bookmarks.spec.ts, __tests__/reducers/windows.spec.ts, app/components/AddressBar/AddressBar.tsx, app/definitions/globals.d.ts, app/extensions/safe/blockNonSafeReqs.ts, app/extensions/safe/components/webIdDropdown/WebIdDropdown.tsx, app/extensions/safe/index.ts, app/openWindow.ts
=> chore(linting): More wee lints and fixes

.travis.yml, app/components/PerusePages/History/History.tsx, app/components/Tab/Tab.tsx, app/extensions/index.ts, app/extensions/safe/components/authRequest.tsx, app/extensions/safe/components/webIdDropdown/WebIdDropdown.tsx, app/extensions/safe/index.ts, app/extensions/safe/server-routes/safe.tsx, app/main.dev.ts, app/menu.ts, app/openWindow.ts, app/reducers/tabs.ts, app/reducers/windows.ts
resloves #767 
Some minor lint fixes, running 
`yarn lint --quiet --ignore-pattern auth-web-app --ignore-pattern ffi/`
Should throw no errors
QA: standard regression
=> chore(linting):Some more lint fixes

__tests__/reducers/windows.spec.ts, app/actions/windows_actions.ts, app/extensions/safe/main-process/onReceiveUrl.ts, app/main.dev.ts, app/openWindow.ts, app/reducers/tabs.ts, app/reducers/windows.ts, app/utils/getMostRecentlyActiveWindow.ts
=> Fix opening urls

.travis.yml
=> fix(CI): Update travis xvfb invocation

.travis.yml
Update branch in deploy section to `dev` to enable RC builds
=> Update branch in deploy to dev to enable RC builds

app/extensions/safe/components/webIdDropdown/WebIdDropdown.tsx
=> fix(webIdDropDown): Fix Error shown on opening a new Window

app/menu.ts
=> Fix for Right click Inspect element broken

app/components/PerusePages/History/History.tsx, app/components/PerusePages/History/history.css, package.json
=> Fix for History TimeStamps

__tests__/actions/history.spec.ts, __tests__/reducers/history.spec.ts, app/actions/history_actions.ts, app/extensions/safe/safeBrowserApplication/manageBrowserConfig.ts, app/reducers/history.ts
=> fix(store): Update History on read state from Network

__testcafe__/resetStore.spec.ts, __tests__/reducers/bookmarks.spec.ts, app/reducers/bookmarks.ts, package.json
resolves #850 
Check if the testcafe test for resetStore passes on running `yarn cafe-e2e`
=> Bookmarks should reset on logout

README.md, package.json
Update to readme about the linux packaging issue
=> chore(readme): Update readme to run linux packaged app

CHANGELOG.md, package.json
=> chore(release): 0.14.0

__testcafe__/helpers.js, __testcafe__/peruse.spec.ts, app/components/Browser/Browser.tsx, app/components/Tab/Tab.tsx, app/menu.ts
resolves #599 
QA:
To test:
1) Open the browser 
2) add a new tab
3) navigate to safe://home.dgeddes
4) add a new tab
5) click on home.dgeddes
6) Right-click on a link and click open link in new tab
7) check if a new tab is added next to the currently active tab rather than at the end
=> "Open link in new tab" opens at end of currently open tabs.

CHANGELOG.md, package.json
=> chore(release): 0.14.1

CHANGELOG.md, __testcafe__/helpers.js, __testcafe__/peruse.spec.ts, app/components/Browser/Browser.tsx, app/components/Tab/Tab.tsx, app/menu.ts, package.json, post-pack.js, yarn.lock
=> Merge dev branch to master

app/menu.ts
No e2e tests due to unstable environment.
Fixes #632 
QA:
Easiest way to test this PR would be to:
```
- Build safe browser
- Open safe browser
- Go to `Window` menu
- Expect to see as first option `Minimise` instead of `Minimize` (British vs. American)
```
=> fix: issue #632 Minimize vs. Minimise

.travis.yml
=> chore(ci): install aws

.travis.yml, app/extensions/safe/defaultNewSite/index.html, yarn.lock
=> chore(bindings): use latest version of safe-nodejs and fix text in default site

app/extensions/safe/reducers/pWeb_reducer.ts
=> Minor fix to store sites right latest version in state

.travis.yml
Attempt to use 10.3 for notarisation, as some reports (https://forums.developer.apple.com/thread/123870) suggest that works.
=> chore(ci): use xcode 10.3

.travis.yml, afterSign.js, app/extensions/safe/manageAndModifyRequests.ts, package.json, yarn.lock
=> Fix history

package.json, yarn.lock
=> chore(deps): downgrade to 6.0.12 for windows builds

.travis.yml, package.json
=> ci(deploys): remove s3 deploy from travis

CHANGELOG.md, package.json
=> chore(release): 0.15.3

.github/workflows/release.yml, .travis.yml
=> Chore release enhancment

CHANGELOG.md, package.json
=> chore(bump): 0.15.4 version bump

CHANGELOG.md, package.json
=> chore(changelog): Update changelog for 0.15.4

CHANGELOG.md
=> chore(release): 0.16.0

package.json
17 skipped as was a lot of alphas, and then _another_ large codechange.
So a distinction here seemed sensible.
=> chore: update v to 18

.github/workflows/bump.yml
stop accidental tag creation if we cannot push changes
=> ci: push changes before tags
