maidsafe/safe-browser

- app/shell-window/pages.js
When in safemode prevents client blocked requests (via the safe filter) from throwing error page.
> fix/safemode: Do not show error page for clearnet navigation [MAID-2158]

- README.md
All the dependencies are now downloaded via pre-compiled binaries, so I think it would make sense to remove Rust as a prerequisite 🙂
> remove Rust as a prerequisite

- app/builtin-pages/views/downloads.js
- app/builtin-pages/views/favorites.js
- app/builtin-pages/views/history.js
- app/builtin-pages/views/settings.js
- app/shell-window/pages.js
When the store updates, there's no longer a hard reload.
Instead pages get window.updateFromStore methods triggered inside the page.
> fix/beaker-reloads: Stops hard reloading of beaker: pages [MAID-2141]

- app/background-process/ui/window-menu.js
Adds the menu item, which opens `safe-logs:list`.
Requires: https://github.com/maidsafe/beaker-plugin-safe-app/pull/57
> feat/log menu: add log list menu item [MAID-2232]

- app/background-process.js
- app/background-process/ui/windows.js
all windows to prevent object destroyed warnings.
(Webcontents was, obv, being destroyed, but the listener was in place)
> fix/osx-store: Ubsubscribe on close [MAID-2287]

- README.md
The instructions that explain how to build the SAFE Browser for mock-routing were removed in [this commit](https://github.com/maidsafe/safe_browser/commit/89e8e199d116f07acf63a7cc34c0a9020fc72af6#diff-04c6e90faac2675aa89e2176d2eec7d8).
I think it could be good to readd them 🙂
> readd NODE_ENV=dev instructions

- app/shell-window/ui/navbar.js
Fetch images with relative path breaks within subfolders, when the address was given without `index.html`. eg `safe://service.publicname/subDir`. 
Fixed this issue.
> Resolve resource fetch issue

- .travis.yml
- appveyor.yml
Adds osx/linux builds for release/mock.
Windows is partially there, working for prod, but naming is still creating a zip with the tag, where it doesn't need to; also there's no conditional prefix of `mock-` yet.
> feat/CI: Add mock to travis builds & update for new build process

- README.md
node-gyp requires Python.
Otherwise `yarn` will result in an error about Python not being found in path.
> Mention requirement of Python in README.md

- app/app.global.css
- app/components/Notifier/Notifier.jsx
- app/extensions/safe/components/authRequest.js
@joshuef At first I tried placing the styles in `notifier.css`, where I noticed them not loaded when `Notifier` is rendered. There are absolutely no styles that will take effect from `notifier.css`. What is that about?
I then tried placing styles in `authReqest.css` and importing it in `authRequest.js`, for which I get parsing error related to babel, which I don't understand yet because the config in `webpack.config.base.js` looks just fine.
> Issue #277 chore/styles: cleans up auth request notificaiton to only show details on hover

- app/extensions/safe/protocols/safe.js
Peruse shouldn't be trying to default a URL with no subdomain as that's handled by the underlying `webFetch` function, specially because this could be changed in the future and it's not the browser responsibility.
> fix/safe-protocol: peruse was defaulting urls with no subdomain to www.<hostname>

- app/package.json
- app/yarn.lock
Solves this issue in the web-id-manager: https://github.com/maidsafe/safe-web-id-manager-js/issues/7
> chore/bump: safe-app-nodejs bumped to latest dev branch version

- app/extensions/safe/auth-web-app/utils.js
Minor fix for an unlikely but possible case when the application's name is just a sequence of `-` and/or `_` characters. In such don't replace theses characters with white spaces. This was causing the whole authenticator page to be a blank screen.
To reproduce it you can authorise an app with the following info and then go to the authenticator tab to see a blank page:
```
window.safe.initialiseApp({
id: 'net.maidsafe.test.webapp.id',
name: '-',
vendor: 'MaidSafe Ltd.'
});
```
> fix(UI): when the app name is just - or _ characters render them in the authenticator as they are

- app/extensions/safe/auth-web-app/sass/auth.scss
- app/extensions/safe/locales/en.json
You may ask why this is necessary.
[This text](https://github.com/maidsafe/safe_browser/blame/b0845742c6a10c2b9bb20bba2acfe069f2a41169/app/extensions/safe/auth-web-app/components/create_account.js#L159) was previously unstyled, simply using `<br>` to format.
It was no longer formatted when moved to `locales/en.json` for `i18n`.
> fix(auth-ui): adds missing padding and fixes grammar

- app/openWindow.js
> fix(browserWindow): Resizable on Windows by removing `thickFrame` option

- app/components/Tab/Tab.jsx
Resolves #524 
QA:
- `yarn prod-dev`
- Navigate to `safe://safenetworkprimer`
- Right-click on any anchor link
- Choose `Open Link in New Tab`
> fix(tabs): Working tab context menu option: 'Open Link in New Tab'

- post-pack.js
Remove unnecessary unlinkSync, which was occuring during post-pack
> fix packaging issue on windows

- app/components/TabBar/TabBar.jsx
- app/components/TabBar/tabBar.css
- app/constants.js
Resolves #586 
```
QA:
The easiest way to test this PR would be to:
-Initialize the browser on Mac OS
-And check if close/minimize icons do not overlap any UI.
(Similarly for windows)
```
> fix top padding based on OS specification

- __tests__/actions/ui.spec.js
- app/actions/ui_actions.js
- app/components/AddressBar/AddressBar.jsx
- app/extensions/safe/test/e2e/safe-bookmark-login-out.network.spec.js
Resolves #562 
Steps to test the resolution.
For example:
```
QA:
The easiest way to test this PR would be to:
-Open a new window
-If upon showing the menu, it doesn't show the menu in all windows of the browser
-If upon reloading the active tab in one window, does not cause the active tabs in other windows to reload as well
-If upon opening history or bookmarks in one window, does not open history and bookmarks in other windows of the browser as well
```
> Show_menu restricted to Current Window only

- __tests__/actions/tabs.spec.js
- __tests__/components/AddressBar.spec.js
- __tests__/components/AddressBarButtonsLHS.spec.js
- __tests__/components/AddressBarButtonsRHS.spec.js
- __tests__/components/AddressBarInput.spec.js
- __tests__/components/Browser.spec.js
- __tests__/components/Tab.spec.js
- __tests__/reducers/tabs.spec.js
- app/actions/tabs_actions.js
- app/actions/ui_actions.js
- app/components/AddressBar/AddressBar.jsx
- app/components/AddressBar/Input/Input.jsx
- app/components/Browser/Browser.jsx
- app/components/Tab/Tab.jsx
- app/components/TabContents/TabContents.jsx
- app/extensions/safe/auth-web-app/containers/login.js
- app/extensions/safe/components/webIdDropdown/WebIdDropdown.js
- app/menu.js
- app/reducers/initialAppState.js
- app/reducers/tabs.js
- app/reducers/ui.js
Closes #567 
Resolves #522 
QA: 
- Cycling through other tabs while other tab(s) are loading shouldn't interrupt/delay loading
- Big refactor, so this PR should be on regression watch.
> Remove activeTab related logic as default behavior

- app/extensions/safe/actions/safeBrowserApplication_actions.ts
QA: fixes https://github.com/maidsafe/safe_browser/issues/620
WebId Dropdown should populate (after a short delay fetching)
> fix(webId): Calls to get webIds fixed.

- app/extensions/safe/test/e2e/safe.spec.ts
- app/webPreload.ts
- yarn.lock
Resolves #628 
QA:
- `yarn build`
- `yarn mock-dev`
- Right-click on tab contents to get `webview` console.
- Test use of `eval` and observe that it is allowed to be used
Also:
`yarn prod-dev`
- Right-click on tab contents to get `webview` console.
- Test use of `eval` and observe that it is not allowed to be used
> refactor(webpreload): Allows eval when browser run against MockVault

- app/extensions/safe/auth-web-app/components/app_list.tsx
Resolves #498 
QA:
- Upon logging in to authenticator, there should no longer be error from from React about missing `key` props.
> fix(auth-app): adds necessary keys to resolve error message

- .travis.yml
- app/extensions/safe/blockNonSafeReqs.ts
- app/extensions/safe/ffi/ipc.ts
- app/extensions/safe/safeBrowserApplication/init/initAuthed.ts
- app/extensions/safe/test/e2e/safe-auth.spec.ts
- app/extensions/safe/test/e2e/safe.spec.ts
- app/main.dev.ts
- app/menu.ts
- package.json
- yarn.lock
Tracking #570 
`open` is actively maintained, so although this `xdg-utils` [commit](https://cgit.freedesktop.org/xdg/xdg-utils/commit/?id=bfcefa162b1dcd6d62e193019969ff2f5ff331cf) is not yet stable released, it will be and `open` maintainers will be on top of it.
> chore(deps): use open instead of shell.openExternal

- app/menu.ts
QA: `Tests` menu should not be visible in dev or prod app development (but should be visible for testcafe tests).
> fix(Menu): Test menu now only shown during testcafe tests

- __e2e__/lib/browser-driver.ts
- app/definitions/globals.d.ts
- app/extensions/safe/auth-api/ffiLoader.ts
- app/extensions/safe/components/webIdDropdown/WebIdDropdown.tsx
- app/extensions/safe/ffi/authenticator.ts
- app/extensions/safe/ffi/lib.ts
- app/extensions/safe/ffi/listeners.ts
- app/extensions/safe/ffi/refs/parsers.ts
- app/extensions/safe/ffi/safe_lib.ts
- app/extensions/safe/safeBrowserApplication/manageBrowserConfig.ts
- app/menu.ts
- package.json
- tsconfig.json
This does some small linting, and sets up the `lint-stage` command to ignore both `FFI`, and `auth-web-app` folders for now (to try and get us on the path to lint checking main browser code first and foremost)
QA: regression tests only.
> chore(linting): Further linting

- app/menu.ts
- yarn.lock
resolves #596
QA: 
To test this PR 
- Open Safe browser
- For Windows keypress, F5 should reload the page
- For Mac OS keypress Ctrl or Command + R should reload the page
This Issue in electron prevents us from adding more than one keyboard shortcut for a particular menu item.
https://github.com/electron/electron/issues/4758
The issue suggests a workaround for this by handling shortcuts with DOM events
But making this does not work as within the webview the keyboard shortcut does nothing. 
https://github.com/electron/electron/blob/master/docs/tutorial/keyboard-shortcuts.md
> feat(reload): F5 for reload

- package.json
Packaging the App on Linux should provide an app Image.
QA-
The best way to test this app is to package the app on Linux and check if an AppImage is Provided to as an executable.
> chore(package): Provide a AppImage for linux

- app/reducers/tabs.ts
resolves #810 
Path to favicon.ico for tabs in packaged app updated
QA-
To test this PR check if the favicon.ico shows up for both package and unpackaged app
> chore(favicon): Update path to tab favicon in packaged app

- app/components/Tab/Tab.tsx
This PR updates the right click menu to show `f5 is the new shortcut to reload a tab for windows and linux, while it is `ctrl+r` for osx
> chore(reload): Change Update Shortcut for reload

- app/components/TabBar/tabBar.css
In the packaged app on loading patter, the tab look like :-
This Pr fixes this issue.
QA-
To test this PR package the app and go to safe://patter.dapp
> chore(tabBar): Update TabBar css to prevent text overflow

- post-pack.js
The logs on windows in the `SAFE_Browser.Maidsafe.net_Ltd` was always null and there weren't any logs being added. This was because of the `log.TOML` file was in the packaged apps resources folder rather than in the being in the same directory as the executable. 
QA to test
1. Package the app on windows
2. Launch the app 
3. Login to the authenticator
4. Log out and close the app
5. Check if logs exist in the `SAFE_Browser.Maidsafe.net_Ltd` file
> fix logs on windows

- app/extensions/safe/manageAndModifyRequests.ts
Properly blocks unversioned NRS sites loaded as resources on another page
fixes #1052
> fix(resolution): External NRS resolution fix.

- resources/entitlements.mac.plist
> Fix notarize perms

- app/autoUpdate.ts
- app/utils/handleNotificiations.tsx
> chore(text): Update notification text improvement
